### ISSUE TITLE
Doc sites doesnt work

### ISSUE THREAD

**Issue by mhzawadi** [rmountjoy92/DashMachine-0.7#2]
Hello,

I have setup the container on my docker host, now to start building a dashboard. but I cant see your doc site.

`Interested in dashmachine.io? Our Domain Broker Service may be able to get it for you. Find out how.` is at the top of the site

**Comment by rmountjoy92** [comment]
Hey! Thanks for trying out 0.7! 

I do own the URL DashMachine.io and am working on the site, but it is not quite ready. It's one of the things keeping me from releasing 0.7. 

The vscode snippets are generated from the toml files in this repo https://www.github.com/rmountjoy92/DashMachineVSCode/tree/master/documentation

The majority of the documentation will essentially just be making the data in those toml files look nice.

**Comment by mhzawadi** [comment]
thats fine, have had a poke and cant seem to make a card.

could I get an example card that goes to a web site

**Comment by rmountjoy92** [comment]
I set up a preview version of what the docs site will look like, and put a few card examples in there. There is a 'basic app card' example, which will give you cards that look much like the card in previous versions. I also included the toml for the 'full card example' I demo'd in the video. They can be found in the 'getting started' dashboard at https://dashmachine7.wolf-house.net/

**Comment by mhzawadi** [comment]
Thamks for that, have got some cards working. your example site site looks cool, by the way
