### ISSUE TITLE
Testing data_sources ping error on args/kwargs

### ISSUE THREAD

**Issue by harakiri85** [rmountjoy92/DashMachine-0.7#4]
Hi,

   I have created a data_sources.toml  with:
```
[ping_test]
platform = 'ping'
resource = '192.168.1.1'
```

And then on my card:
['TestCard']
title = 'Test Card'
data_sources.sources = ['ping_test']

It was showing error "Platform process method failed". Error = "'Platform' object has no attribute 'resource'"

I found that on the platform/ping.py, the parameters are being passed on the "args" variable, not the kwargs, so I had to do this:
```
    def __init__(self, *args, **kwargs):
        # parse the user's options from the config entries
        kwargs = args[0]
        for key, value in kwargs.items():
            self.__dict__[key] = value

```

Not sure if you are planning to use args for all the functions or is was only this case with the "ping" platform.

On the old 0.6, definitely you were using kwargs. Not sure were you are passing the params on the 0.7 data_source_handler.py
https://github.com/rmountjoy92/DashMachine/blob/be50c2e763ae4e18f95855c18ba31c42199a4b3e/dashmachine/main/utils.py#L93
Old 0.6 utils.py   ->    platform = module.Platform(data_source, **data_source_args)

P.S. Incredible project you are doing. Love it!

**Comment by rmountjoy92** [comment]
Hey! Thanks! :)

So yeah, for better readability, only a single argument is passed in as the `options` dict. This dict contains all the params from the config, if you look at weather.py, it's the only one where I've made the change. It looks like this:
```
class Platform:
    def __init__(self, options):
        # parse the user's options from the config entries
        for key, value in options.items():
            setattr(self, key, value)
```
Until I get to going through all of the platforms and fixing them, you could drop in a custom version into config/platform (needs a unique name like `ping1.py` with the update and call it like normal `platform = 'ping1'`

The data source handler is now it's own class/file, all things data source/platform related can be found in:
https://github.com/rmountjoy92/DashMachine-0.7/blob/master/dashmachine/dm/data_source_handler.py

Hope this helps! :)

**Comment by harakiri85** [comment]
OK I see, sorry to bother you. I went to the one I thought it was the simplest to test. 
Great, I will do that, save it as a new platform and have a play.

**Comment by rmountjoy92** [comment]
No worries!! Thanks for testing! <3

**Comment by jvteleco** [comment]
Hi, I created a PR changing several platforms to include the new options dict as well as the pihole changes I submitted for 0.6.
Feel free to correct.

Happy to give you a hand updating the other platforms which I can cope with my basic python. That way you can concentrate on the difficult code.
Cheers

**Comment by rmountjoy92** [comment]
@jvteleco Thanks man, seriously appreciated. Closing.
