### ISSUE TITLE
Card.full-width=true  is not being applied to the css in the html output

### ISSUE THREAD

**Issue by rmensing** [rmountjoy92/DashMachine-0.7#8]
The following is one of the entries in my main.toml:
```
['Servers']
title = 'Servers'
full-width = true
```
Which, based on my rusty Python/Flask, should apply the following:
```
(dm/dashboard_card/__init__.py ) line 48

self.card["width"] = "calc(100vw - 2rem)"
```
And applied in the template:
```
(templates/main/dashboard.html ) line 7-8

style="
     width: {{ dashboard_card.card.get('width', '') }};
```
But, in the html output to the browser I get the following:
`<div class="grid-item card shadow-sm text-center" data-searchable="Servers~Servers~" data-tags="" style="width: auto; position: absolute; left: 0px; top: 0px;">`

where style= "width: auto;"
If I edit it in the browser dev tools and enter the proper width calc it displays correctly.

**Comment by rmountjoy92** [comment]
Hey!

Thanks for reporting! The documentation was wrong,
instead of:
```
full-width = true
```
it needs to be
```
card.full-width = true
```
