### ISSUE TITLE
custom icons cannot be used

### ISSUE THREAD

**Issue by trenetics** [rmountjoy92/DashMachine-0.7#9]
If I put some external icons in the icons folder I can't link to them to /static/assets/images/any_file_from_assets.png doesn't work

would be nice if I could use costum icons for apps that aren't in: icon = 'static/images/apps/xxx.png'

**Comment by rmountjoy92** [comment]
```
['empty card']
icon = 'static/user_assets/images/any_file_from_assets.png'
```

Seems to be working fine for me

**Comment by trenetics** [comment]
> ```
> ['empty card']
> icon = 'static/user_assets/images/any_file_from_assets.png'
> ```
> 
> Seems to be working fine for me

where do you place the icons you want to use then? if i place them in /static/assets/images/ and make a folder called apps there, place my 100 icons and try to link to them using lets say: /static/assets/images/apps/xxx.png (doesn't display the icon)

Maybe im doing something wrong?

**Comment by rmountjoy92** [comment]
`config/assets` gets symlinked to `static/user_assets` Anything you put in there is served via `/static/`

`config/assets/images/apps/xxx.png`
is the same as
`static/user_assets/images/apps/xxx.png`

But in your config it has to be the static path, as flask serves assets from the /static/ folder

**Comment by trenetics** [comment]
> ```
> ['empty card']
> icon = 'static/user_assets/images/any_file_from_assets.png'
> ```
> 
> Seems to be working fine for me

where do you place the icons you want to use then? if i place them in /static/assets/images/ and make a folder called apps there, place my 100 icons and try to link to them using lets say: /static/assets/images/apps/xxx.png (doesn't display the icon)

Maybe im doing something wrong?

> `config/assets` gets symlinked to `static/user_assets` Anything you put in there is served via `/static/`
> 
> `config/assets/images/apps/xxx.png`
> is the same as
> `static/user_assets/images/apps/xxx.png`
> 
> But in your config it has to be the static path, as flask serves assets from the /static/ folder

Yea, i can't seem to get it to work:

here's my config:

![image](https://user-images.githubusercontent.com/56591389/95452905-45f80e80-096a-11eb-8419-c46107413dad.png)

when i load my dash it looks like this:

![image](https://user-images.githubusercontent.com/56591389/95452959-5c05cf00-096a-11eb-8a3a-784f44c1b023.png)

as you can see i placed the icons files:

![image](https://user-images.githubusercontent.com/56591389/95453018-7049cc00-096a-11eb-9490-5d57a681a155.png)

and if i try to load the image: http://192.168.1.56:5000/static/images/librenms.png

![image](https://user-images.githubusercontent.com/56591389/95453077-835c9c00-096a-11eb-90ac-b8dde4a6b97d.png)

So something is not working correctly. :-/

**Comment by rmountjoy92** [comment]
I don't mean to be rude, but did you read my response?

Your config should be:
```
['Diag-Instances']
icon = 'static/user_assets/images/librenms.png'
```

**Comment by trenetics** [comment]
> I don't mean to be rude, but did you read my response?
> 
> Your config should be:
> 
> ```
> ['Diag-Instances']
> icon = 'static/user_assets/images/librenms.png'
> ```

ah sry buddy must hav missed that one.. :-/ my bad

**Comment by trenetics** [comment]
Works perfectly by the way! Thanks!
